### PR TITLE
Holiday 2015

### PR DESCRIPTION
**Pull request by nelsonjchen**
https://trello.com/c/2wX3hePp/241-take-down-sb-marathon-webpages

https://trello.com/c/SnHrNgXH/243-replace-shop-and-bssp-banners-on-home-page-with-these-2-banners

https://trello.com/c/X8i3xoFd/242-remove-sb-marathon-from-the-header-buttons

### CODE REVIEW

**Comment by nelsonjchen** [comment]
@homu r+

**Comment by nelsonjchen** [comment]
@homu retry

**Comment by barosl** [comment]
Hi! Sorry for off-topic, but I noticed that an internal error had occurred while processing this PR in Homu. It seems that the issue is related to the recently added protected branches feature. Did you turn **off** the feature before `retry`ing this PR again? Or did it just work without changing any repository configuration (leaving the branch protection turned on)?

**Comment by nelsonjchen** [comment]
Ah no, I didn't turn it off. In fact, it appear to just merge immediately after I asked it to retry which was weird.

**Comment by barosl** [comment]
Ah, that's an intended behavior. It's the newly added ["test exemption" feature](https://github.com/barosl/homu/commit/1ad70672fd78da07414c577a1d1ba6e07b001d0e). If Homu finds no other PRs have been merged into `master` since the creation of a PR, it can reuse the test result on the PR itself (which is also reported by Travis). So it can reduce the time taken to test short-lived PRs. However, if you try to merge multiple PRs at once, it will only skip the test for the first PR and keep testing the remaining PRs.

**Pull request merged**
